workflows:
  ios-build:
    name: iOS Build Workflow for Xcode 16.1 and iOS 18.1
    max_build_duration: 60 # Set max build duration in minutes
    platform: ios
    sdk: iphoneos # Use iPhone OS SDK for building
    xcode: 16.1 # Specify the Xcode version as 16.1
    environment:
      vars:
        FLUTTER_VERSION: '3.0.0'  # Example, if you're using Flutter, set your version
    steps:
      # Checkout source code from GitHub
      - checkout:
          repository: https://github.com/bonJesse/SangDee.git
      
      # Navigate to the iOS project directory
      - run:
          name: Install dependencies (CocoaPods)
          command: |
            cd SangDee/SangDee-iOS
            gem install cocoapods
            pod install
            
      # Build the app (using xcodebuild)
      - run:
          name: Build iOS App
          command: |
            cd SangDee/SangDee-iOS
            xcodebuild clean build -workspace SangDee.xcworkspace -scheme SangDee-iOS -sdk iphoneos

      # Export the .ipa file
      - run:
          name: Export .ipa
          command: |
            cd SangDee/SangDee-iOS
            xcodebuild -exportArchive -archivePath $PWD/build/ios/iphoneos/SangDee-iOS.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/ipa
            
      # Upload the .ipa file to Artifacts
      - upload:
          artifact: SangDee/SangDee-iOS/build/ipa/*.ipa
          name: ipa
