workflows:
  ios-build:
    name: iOS Build Workflow for Xcode 16.1 and iOS 18.1
    max_build_duration: 60 # Set max build duration in minutes
    scripts:
      # Checkout the repository
      - "git clone https://github.com/bonJesse/SangDee.git"

      # Install dependencies (CocoaPods)
      - |
        cd SangDee/SangDee-iOS
        gem install cocoapods
        pod install

      # Build the app using xcodebuild
      - |
        cd SangDee/SangDee-iOS
        xcodebuild clean build -workspace SangDee.xcworkspace -scheme SangDee-iOS -sdk iphoneos

      # Export the .ipa file
      - |
        cd SangDee/SangDee-iOS
        xcodebuild -exportArchive -archivePath $PWD/build/ios/iphoneos/SangDee-iOS.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/ipa

      # Upload the .ipa file to Artifacts
      - |
        cd SangDee/SangDee-iOS
        mv build/ipa/*.ipa $CM_IPA_OUTPUT
        cp $CM_IPA_OUTPUT /artifacts/ipa/
