workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        # Apple Developer Team ID
        APPLE_DEVELOPER_TEAM_ID: $APPLE_DEVELOPER_TEAM_ID
        # Apple Distribution Certificate and Provisioning Profiles
        CERTIFICATE_PRIVATE_KEY: $CERTIFICATE_PRIVATE_KEY
        CERTIFICATE_PASSWORD: $CERTIFICATE_PASSWORD
        APP_STORE_CONNECT_API_KEY: $APP_STORE_CONNECT_API_KEY
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Clone repository
        script: |
          git clone https://github.com/bonJesse/SangDee.git
          cd SangDee/SangDee-iOS
      
      - name: Install dependencies
        script: |
          # Check if CocoaPods is installed
          if ! which pod > /dev/null; then
            sudo gem install cocoapods
          fi
          pod install
      
      - name: Set up permissions
        script: |
          chmod +x ./*.sh
          chmod +x ./SangDee/SangDee-iOS
      
      - name: Build the iOS app
        script: |
          xcodebuild clean
          xcodebuild -workspace SangDee-iOS.xcworkspace -scheme SangDee-iOS -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="Apple Distribution" -allowProvisioningUpdates
      
    artifacts:
      - build/ios/Release-iphoneos/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        api_key: $APP_STORE_CONNECT_API_KEY
        api_issuer_id: $APP_STORE_CONNECT_API_ISSUER_ID
        app_identifier: $IOS_APP_BUNDLE_ID
        submit_to_testflight: true
        release_type: beta

    dependencies:
      cache:
        # Enable dependency caching
        cache_paths:
          - ~/Library/Developer/Xcode/DerivedData
          - Pods
          - .gradle
          - node_modules
          - Carthage
          - SangDee/SangDee-iOS/Carthage
          - ~/Library/Caches/com.apple.dt.Xcode
          - ~/Library/Caches/org.carthage.CarthageKit
          - ~/Library/Caches/Homebrew
