name: SangDee
options:
  bundleIdPrefix: com.sangdee
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "16.1"

settings:
  base:
    DEVELOPMENT_TEAM: YOUR_TEAM_ID
    PRODUCT_BUNDLE_IDENTIFIER: com.sangdee.app

targets:
  SangDee:
    type: application
    platform: iOS
    sources:
      - path: SangDee
    resources:
      - path: SangDee/Resources/Assets.xcassets
        type: folder
    settings:
      base:
        INFOPLIST_FILE: SangDee/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.sangdee.app
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        SWIFT_VERSION: 5.0
        ENABLE_BITCODE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - sdk: UIKit.framework
      - sdk: AVFoundation.framework
      - package: SnapKit
      - package: RxSwift
      - package: RxCocoa

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    exactVersion: 5.6.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    exactVersion: 6.6.0
  RxCocoa:
    url: https://github.com/ReactiveX/RxSwift
    exactVersion: 6.6.0